# -*- coding: utf-8 -*-
"""Day_15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWO266oNFiZ4p3kSEUVkI1UkPS9SXp5i

# **Creating a Dictionary**
"""

student = {}

# List - []
# Dict - {}

# name, age, gender
student = {"name":"Raju", "age":27, "gender":"male", "qualified":False}

# key-value pairs - 3
# key & value are linked using :

print(student)

"""# 2. **Accessing Values**"""

student["name"]

student["name"] = "David"
student["age"] = 26

student

"""# **3. Looping Through a Dictionary**"""

student

for key in student:
  print(key)

for value in student.values():
  print(value)

for k, v in student.items():
  print(k, v)

for k in student:
  if k == "name":
    print("Found the key")

if "hobby" in student:
  print(True)
else:
  print(False)