# -*- coding: utf-8 -*-
"""Day_08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jp7K89iekvVVDI_kxUGWHtFuuo4H9YI1

# **Functions - Basics**
"""

# input, logic, output

print("Hello David!")

"""# **1. Defining a Function**"""

def hello():
  print("Hello world!")

"""# **2. Calling a Function**"""

hello()

# input - inside braces - no
# logic - print
# output - Hello world

"""# **3. Function with Parameters / Params**"""

def hello(name):
  print(f"Hello {name}!")

hello("Rajesh")

"""# **F Strings**"""

country = "Australia"
capital = "Canberra"
print(f"{capital} is the capital city of {country}")

"""# **4. Function with Return value**"""

# two numbers = add them
def add_numbers(x, y):
  return x+y

add_numbers(5, 6)

v = add_numbers(5, 6)

v