# -*- coding: utf-8 -*-
"""Day_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i06k3DcUVb83c2jf4uxJvynfxIhqn0_8
"""

ticket_price = 90
wallet_size = 100

# Ctrl + Enter (run)
# Comparision <, >, <=, >=, ==, !=

if ticket_price <= wallet_size:
  print("Hurray, i can go to this movie!")
else:
  print("Sad, i don't have enough purse")

# if (condition):
#   # to do
# else:
#   # to do

marks = 85

# 90+ A+
# 80+ A
# 70+ B+
# 60+ B
# 60- Fail

# if else elif

marks = 40

if (marks >= 90):
  print("A+")
elif (marks >= 80):
  print("A")
elif (marks >= 70):
  print("B+")
elif (marks >= 60):
  print("B")
else:
  print("Fail")











