# -*- coding: utf-8 -*-
"""Day_11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_eoUBC131t2KQPHzS-PpmQHZU-arfTby
"""



"""# **Error Handling in Python**"""

print("Hello World"

2 + "Hello"

y

ls = [1,2,3]

ls[3]

d1 = {'k1':'v1'}

d1['k2']

int(2.3)

int("Hello")

10/0

# try except

try:
  result = 10/0
except ZeroDivisionError:
  print("Error: Cannot divide by zero")

try:
  x = int("Hello")
except ValueError:
  print("Error: Please input appropriate value")

x = int("Hello")
y = 2+3

try:
  x = int("Hello")
except ValueError:
  print("Error: Please input appropriate value")

y = 2 + 3

y