# -*- coding: utf-8 -*-
"""Day_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5PjvSkXYnXPvBeSvpfrbQNNOt1gt-qE
"""



"""# **1. Creating Strings**"""

single_quote_strings = 'Hello'
double_quote_strings = "Hello"
triple_quote_strings = '''Hello'''

multiline_string = '''
this is line 1 in my story
this is line 2 in my story
'''

"""# **2. Accessing Char**"""

single_quote_strings[1]

"""# **3. Slicing a String**"""

single_quote_strings[:4]

multiline_string[:15]

"""# **4. Negative indexing**"""

double_quote_strings[-1]

"""# **5. String Concatenation**"""

"Hello" + " " + "World" + "!"

"""# **6. String Repetition**"""

"ha "*3 + '!'

"""# **7. String length**"""

x = "Hello "

len(x)

"""# **8. Checking Substrings**"""

# substring - string which is a part of the main string
# "Hello World" --> "World"

x = " HelloWorld"

print(" " in x)

"""# 9. **String Methods / Functions**"""

name = "david"

# name.lower()
name.upper()

# join, strip, split, replace



"""# 10. **String Formatting - F String**"""

name = "Sachin"
print(f"My name is {name}")