# -*- coding: utf-8 -*-
"""Day_16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19oYZ2PMML3mI0siXBtAFX_5uot6IoGmI
"""

# List [,]
# Dict {key:value}
# Tuple (,)
# Set {,}



"""# **Creating a Tuple**"""

my_tuple = (1, 2, 3)

my_tuple

"""# **Accessing Tuple Elements**"""

my_tuple[2]

"""# **Tuple Operations**"""

tp1 = (1, 2, 3)
tp2 = ("a", "b", "c")

tp3 = (1,)

tp3*10

"""# **Tuple Unpacking**"""

tp1 = (1, 2, 3)

a = 1
b = 2
c = 3

a, b, c = (10, 20, 30)

b

"""# **List vs Tuple**"""

# List - Train - Mutable (add, remove, modify, ..)
# Tuple - Bus - Immutable (can't add, can't remove, ..)

# List - memory high
# Tuple - memory low

"""# **Sets**"""

ls1 = [1, 1, 2]

# unique values in a list
set(ls1)

s1 = {1, 2, 3}

s2 = {2, 3, 4}

"""# **Set Operations**"""

s1.union(s2)

s1.intersection(s2)

s1.difference(s2)

s2.difference(s1)

