# -*- coding: utf-8 -*-
"""Day_17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157ukvEiPTqFxO4xo0Y1_dYNr9mCIcJhI
"""



"""# **Python Modules**"""

# math, random
# Python library / Python module

import math

math.sqrt(100)

math.pi

math.pow(2, 10)

math.factorial(5)

import math as m

m.pow(2,6)

import random

random.random()

random.randint(1000, 9999)

ls1 = ["black", "blue" , "yellow", "green", "grey", "white"]

random.shuffle(ls1)

ls1

ls2 = ["c1", "c2", "c3", "c4", "c5", "c6", "c7"]

random.shuffle(ls2)

ls2

# random.sample, choice - multiple

# libraries - os, json, requests