# -*- coding: utf-8 -*-
"""Day_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15knitOVbIuoCNq_ll0b3qBfreY_KdHCO
"""

# for, range(start, end), in

# by default start = 0, range(20)

print(1)

print(2)

# for i in range(100):
#   print(i)

# n/10 --> reminder of 0

num = 70

if (num%10) == 0:
  print(num)
else:
  print("")

for i in range(100):
  if (i%20) == 0:
    print("divisible: ", i)
  else:
    print("not divisible: ", i)

