# -*- coding: utf-8 -*-
"""Day_05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2npI6CCID-xWR3CRfdBGhZ45yPS0I18

# **Creating a List**
"""

items = []

items = ["speaker", "mic", "mobile", "laptop"]

"""# **Accessing Elements**"""

items[2]

print(items[2])

"""# **Negative Indexing**"""

items[-1]

"""# **Slicing a List**"""

items[0:3]

items

items[2:4]

items[2:]

"""# **Modifying elements in a List**"""

items

items[3] = "pc"

items

"""# **Adding Elements to a List**"""

items

items.append("charger")

items

items.append("camera")

items

"""# **Remove elements**"""

items.remove("camera")

items

del items[-1]

items

items.clear()

items

items = ['speaker', 'mic', 'mobile', 'pc', 'charger']

"""# **Checking for existense**"""

# are earbuds in the list?
print("earbuds" in items)

"""# **Length of a List**"""

items

len(items)

"""# **List comprehension**"""

scores = [70, 80, 90, 95]

for i in scores:
  print(i/2)

[i/2 for i in scores]



